### ISSUE TITLE
ACE reader issue

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#116]
@bhargav need your comment on this. 

I was trying to use the ACE reader to read [this data](winodata) which is written (almost) in ACE format. 
I am getting the following errors: 
```
[info] 	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
[info] 	at java.util.ArrayList.get(ArrayList.java:429)
[info] 	at edu.illinois.cs.cogcomp.nlp.corpusreaders.ACEReader.updateCurrentFiles(ACEReader.java:148)
[info] 	at edu.illinois.cs.cogcomp.nlp.corpusreaders.ACEReader.<init>(ACEReader.java:97)
[info] 	at edu.illinois.cs.cogcomp.nlp.corpusreaders.ACEReader.<init>(ACEReader.java:108)
[info] 	at edu.illinois.cs.cogcomp.saulexamples.nlp.Winograd.WinogradSensors$.readWinoCoref(WinogradSensors.scala:9)
[info] 	at edu.illinois.cs.cogcomp.saulexamples.nlp.Winograd.WinogradApp$.main(WinogradApp.scala:13)
[info] 	at edu.illinois.cs.cogcomp.saulexamples.nlp.Winograd.WinogradApp.main(WinogradApp.scala)
[info] 10:03:35 WARN  ACEReader:150 - Error while reading document - 448.apf.xml
[info] java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[info] 	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
[info] 	at java.util.ArrayList.get(ArrayList.java:429)
[info] 	at edu.illinois.cs.cogcomp.nlp.corpusreaders.ACEReader.updateCurrentFiles(ACEReader.java:148)
[info] 	at edu.illinois.cs.cogcomp.nlp.corpusreaders.ACEReader.<init>(ACEReader.java:97)
[info] 	at edu.illinois.cs.cogcomp.nlp.corpusreaders.ACEReader.<init>(ACEReader.java:108)
[info] 	at edu.illinois.cs.cogcomp.saulexamples.nlp.Winograd.WinogradSensors$.readWinoCoref(WinogradSensors.scala:9)
[info] 	at edu.illinois.cs.cogcomp.saulexamples.nlp.Winograd.WinogradApp$.main(WinogradApp.scala:13)
[info] 	at edu.illinois.cs.cogcomp.saulexamples.nlp.Winograd.WinogradApp.main(WinogradApp.scala)
[info] 10:03:35 WARN  ACEReader:150 - Error while reading document - 449.apf.xml
[info] java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[info] 	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
[info] 	at java.util.ArrayList.get(ArrayList.java:429)
[info] 	at edu.illinois.cs.cogcomp.nlp.corpusreaders.ACEReader.updateCurrentFiles(ACEReader.java:148)
[info] 	at edu.illinois.cs.cogcomp.nlp.corpusreaders.ACEReader.<init>(ACEReader.java:97)
[info] 	at edu.illinois.cs.cogcomp.nlp.corpusreaders.ACEReader.<init>(ACEReader.java:108)
[info] 	at edu.illinois.cs.cogcomp.saulexamples.nlp.Winograd.WinogradSensors$.readWinoCoref(WinogradSensors.scala:9)
[info] 	at edu.illinois.cs.cogcomp.saulexamples.nlp.Winograd.WinogradApp$.main(WinogradApp.scala:13)
[info] 	at edu.illinois.cs.cogcomp.saulexamples.nlp.Winograd.WinogradApp.main(WinogradApp.scala)
[info] 10:03:35 WARN  ACEReader:150 - Error while reading document - 45.apf.xml
[info] java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[info] 	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
[info] 	at java.util.ArrayList.get(ArrayList.java:429)
[info] 	at edu.illinois.cs.cogcomp.nlp.corpusreaders.ACEReader.updateCurrentFiles(ACEReader.java:148)
[info] 	at edu.illinois.cs.cogcomp.nlp.corpusreaders.ACEReader.<init>(ACEReader.java:97)
[info] 	at edu.illinois.cs.cogcomp.nlp.corpusreaders.ACEReader.<init>(ACEReader.java:108)
[info] 	at edu.illinois.cs.cogcomp.saulexamples.nlp.Winograd.WinogradSensors$.readWinoCoref(WinogradSensors.scala:9)
[info] 	at edu.illinois.cs.cogcomp.saulexamples.nlp.Winograd.WinogradApp$.main(WinogradApp.scala:13)
[info] 	at edu.illinois.cs.cogcomp.saulexamples.nlp.Winograd.WinogradApp.main(WinogradApp.scala)
[info] 10:03:35 WARN  ACEReader:150 - Error while reading document - 450.apf.xml
[info] java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
```

Do any of these look familiar? 
I tried to dig into the reader, but it was such a painful experience! :D

**Comment by bhargav** [comment]
You can put a breakpoint here: https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/corpusreaders/src/main/java/edu/illinois/cs/cogcomp/nlp/corpusreaders/aceReader/documentReader/ReadACEAnnotation.java#L32 and trace the function along to see where the parsing fails.

Alternatively, if you can send me a sample document on Email/Slack, I can check.

**Comment by danyaljj** [comment]
Yup I did, but then things turned dark :D 

Here is a sample doc: 

0.apf.xml: 
```
<?xml version="1.0"?> 
 <!DOCTYPE source_file SYSTEM "alf.v4.0.1.dtd"> 
<source_file URI="APW20001001.2021.0521.sgm" SOURCE="newswire" TYPE="text" VERSION="4.0" AUTHOR="LDC" ENCODING="UTF-8">
 <document DOCID="0">
<entity ID="1" TYPE="unknown" SUBTYPE="" CLASS="SPC">
<entity_mention ID="1-1"  TYPE="PRO" LDCTYPE="PRO">
<extent>
<charseq START="47" END="48">it</charseq>
</extent>
<head>
<charseq START="47" END="48">it</charseq>
</head>
</entity_mention>
<entity_mention ID="1-2"  TYPE="NAM" LDCTYPE="NAM" >
<extent>
<charseq START="28" END="37">the flower</charseq>
</extent>
<head>
<charseq START="28" END="37">the flower</charseq>
</head>
</entity_mention>
</entity>
<entity ID="2" TYPE="PER" SUBTYPE="" CLASS="SPC">
<entity_mention ID="1-3"  TYPE="NAM" LDCTYPE="NAM" >
<extent>
<charseq START="10" END="16">The bee</charseq>
</extent>
<head>
<charseq START="10" END="16">The bee</charseq>
</head>
</entity_mention>
</entity></document>
</source_file>
```

0.sgm: 
```
<DOC>
<DOCNO>0</DOCNO>
<DOCTYPE SOURCE="newswire"></DOCTYPE>
<DATE_TIME></DATE_TIME>
<BODY>
<SLUG></SLUG>
<HEADLINE>
</HEADLINE>
<TEXT>
The bee landed on the flower because it had pollen.
</TEXT>
</BODY>
</DOC>
```

**Comment by danyaljj** [comment]
The input data was not standard ACE data. So I deem this irrelevant. Closing it ...
