### ISSUE TITLE
Chunker, NER: method to return set of tags/relation labels that an Annotator can assign

### ISSUE THREAD

**Issue by mssammon** [IllinoisCogComp/illinois-cogcomp-nlp#237]
programmatically provide tag set via Annotator class interface. Implement default in Annotator
(empty tag set, warning "not yet implemented") and override in module subclass,
return set of strings corresponding to tags.
Do this for relations also. (will be empty set for many NLP modules).

**Comment by danyaljj** [comment]
@tofuwen has already implemented this for `Annotator`: 
https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/annotation/Annotator.java#L197-L200

The task is to implement this for all the modules that exist in the super-project?

**Comment by mssammon** [comment]
Yes-- the task is to add the functionality for Chunker and NER.  It has already been implemented for POS. @tofuwen , please also add a test for each that verifies that the method is correctly implemented.

**Comment by danyaljj** [comment]
@tofuwen made any progress on this?

**Comment by tofuwen** [comment]
I am working my project for the past week. I will do this today.

**Comment by tofuwen** [comment]
I am almost done for Chunker.

But when I call "doInitialize", there is error:

java.lang.IllegalArgumentException: ERROR: ResourceLoader.getString(): no entry for key 'modelPath'.

	at edu.illinois.cs.cogcomp.core.utilities.configuration.ResourceManager.getString(ResourceManager.java:149)
	at edu.illinois.cs.cogcomp.chunker.main.ChunkerAnnotator.initialize(ChunkerAnnotator.java:66)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:121)
	at edu.illinois.cs.cogcomp.chunker.main.ChunkerAnnotator.getTagValues(ChunkerAnnotator.java:171)
	at edu.illinois.cs.cogcomp.lbj.chunk.tests.TestDiff.testGetTagValues(TestDiff.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:81)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:130)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

If I don't call "doInitialize", I can get the tag values without any troubles. 

But I think "doInitialize" should work, is this a known issue?

**Comment by mssammon** [comment]
doInitialize() should get called automatically by the Annotator superclass when you first call getView(). You should make sure the constructor instantiates the ChunkerConfigurator -- https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/chunker/src/main/java/edu/illinois/cs/cogcomp/chunker/main/ChunkerConfigurator.java
-- and that the correct field is being populated

**Comment by mssammon** [comment]
closed by #245
