### ISSUE TITLE
Brown clusters not loading from another code 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#99]
Tried load brown clusters from another project but didn't find the resource files:
```
[error] SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[error] Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: brownBllipClusters (No such file or directory)
[error] 	at edu.illinois.cs.cogcomp.edison.annotators.BrownClusterViewGenerator.lazyLoadClusters(BrownClusterViewGenerator.java:199)
[error] 	at edu.illinois.cs.cogcomp.edison.annotators.BrownClusterViewGenerator.addView(BrownClusterViewGenerator.java:150)
[error] 	at edu.illinois.cs.cogcomp.annotation.Annotator.getView(Annotator.java:68)
[error] 	at edu.illinois.cs.cogcomp.edison.features.factory.BrownClusterFeatureExtractor.getWordFeatures(BrownClusterFeatureExtractor.java:112)
[error] 	at edu.illinois.cs.cogcomp.edison.features.WordFeatureExtractor.getFeatures(WordFeatureExtractor.java:79)
[error] 	at org.allenai.ari.solvers.termselector.EssentialTermsSensors$.main(EssentialTermsSensors.scala:414)
[error] 	at org.allenai.ari.solvers.termselector.EssentialTermsSensors.main(EssentialTermsSensors.scala)
[error] Caused by: java.io.FileNotFoundException: brownBllipClusters (No such file or directory)
[error] 	at java.io.FileInputStream.open0(Native Method)
[error] 	at java.io.FileInputStream.open(FileInputStream.java:195)
[error] 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[error] 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
[error] 	at edu.illinois.cs.cogcomp.edison.annotators.BrownClusterViewGenerator.loadClusters(BrownClusterViewGenerator.java:88)
[error] 	at edu.illinois.cs.cogcomp.edison.annotators.BrownClusterViewGenerator.lazyLoadClusters(BrownClusterViewGenerator.java:197)
[error] 	... 6 more
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last termselector/compile:run for the full output.
[error] (termselector/compile:run) Nonzero exit code returned from runner: 1
[error] Total time: 7 s, completed May 29, 2016 8:01:27 AM
```

Here is the code snippet: 
```scala 
   val a = DummyTextAnnotationGenerator.generateBasicTextAnnotation(1)
    val brownClusterFeatureExtractor = WordFeatureExtractorFactory.getBrownFeatureGenerator("", "brownBllipClusters", Array[Int](4, 5))
    brownClusterFeatureExtractor.getFeatures(a.getView(ViewNames.TOKENS).asScala.head)
```

**Comment by christos-c** [comment]
Are you sure brownBllipClusters is a resource? Right now, I can only see it under `test/resources`. Have you checked whether it's part of `common-resources`?

**Comment by danyaljj** [comment]
Seems like it is part of common-resources: 
![screen shot 2016-05-31 at 9 14 49 am](https://cloud.githubusercontent.com/assets/2441454/15681951/36c67a50-2710-11e6-8027-62990daf649e.png)

**Comment by christos-c** [comment]
So it's not `getBrownFeatureGenerator("", "brownBllipClusters", Array[Int](4, 5))`. It should be `getBrownFeatureGenerator("", "brown-clusters/brownBllipClusters", Array[Int](4, 5))`

**Comment by danyaljj** [comment]
Correct that should be it. I'll give it a try and make sure it works.

**Comment by danyaljj** [comment]
Verified the issue; works .... Closing the issue.
